### ISSUE TITLE
Breakage in 03/18 Beta

### ISSUE THREAD

**Issue by ismig** [mgsloan/todoist-shortcuts#111]
The latest Beta broke a bunch of shortcuts. \o/

- These keys don't work on a focused task; they just bring up the scheduling dialog. But they do work on a _selected_ task.
  - **v** (move task to project)
  - **1/2/3/4/0** (change priority)
  - **&** (duplicate a task)
- **G** (navigate to task's project)
- ***a** selects all tasks in view, but also creates a new task at the bottom.
- **?** opens up the todoist-shortcuts guide but also opens and focuses a new tab with Todoist's keyboard shortcuts [guide](http://get.todoist.help/hc/en-us/articles/205063212)
- **esc** doesn't exit from the todoist-shortcuts guide

**Comment by mgsloan** [comment]
Hey, thanks so much for your report!

I've just released version 73 which fixes an initialization bug that could cause all kinds of problems. With that version these keystrokes work for me. Can you please check again with latest beta version / extension version? Thanks!

Another possibility is that it is some difference between how keystrokes are being handled in your browser vs mine.  There have been some other reports of funny behavior related to keystroke handling problems that I don't see

**Comment by ismig** [comment]
Yup, v73 fixes the most important shortcuts. Thanks a lot!

These ones (from the ones I listed above) are still not working for me:
- ***a**
- **?**
- **esc**

**Comment by mgsloan** [comment]
Curiously, it looks like todoist is registering document.onkeydown / onkeyup handlers again after initialization.  I can't predict when this happens, so instead I've just had the code update those all the time (which should be very efficient, it's just setting 3 variables)

**Comment by mgsloan** [comment]
I've released v74 which I think fixes the others.  How's it looking for you?

**Comment by ismig** [comment]
Hurrah, all fixed with v74! Thank you!

**Comment by mgsloan** [comment]
You're welcome, thanks for reporting!
