### ISSUE TITLE
navigateToTask is broken

### ISSUE THREAD

**Issue by ismig** [mgsloan/todoist-shortcuts#144]
In filter or label view mode, typing **G** no longer navigates to the current task's project. Instead, I get this error:
`todoist-shortcuts: Not switching to "Upcoming", because this task is not scheduled. (this is fine)`.
<Insert obligatory "this is fine" meme> :smile: 

Looking at the [code](https://github.com/mgsloan/todoist-shortcuts/blob/abafa66b70bff2d3704c207e4bc1e08559df540d/src/todoist-shortcuts.js#L931), todoist-shortcuts apparently thinks I'm in project view mode.
This happens both in beta and not.

**Comment by ismig** [comment]
Oh, here's another possibly related issue. In filter/label view mode, when I key or mouse over the task list, the console spews an error with `storeCursorContext` in the stack trace.

![where_is_div](https://user-images.githubusercontent.com/40349450/85935313-29950200-b8a4-11ea-9594-0453158aa71b.png)

**Comment by mgsloan** [comment]
Ah, thanks for reporting!  Indeed, the issue was the section finding code hadn't been updated to the new DOM.  Fixed in version 91

**Comment by ismig** [comment]
The fix for this hasn't worked, unfortunately. :(

- It doesn't work in filter view. I still see [this message](https://github.com/mgsloan/todoist-shortcuts/blob/master/src/todoist-shortcuts.js#L929), since [viewMode](https://github.com/mgsloan/todoist-shortcuts/blob/master/src/todoist-shortcuts.js#L917) == 'project', which is wrong.
- It _does_ work in label view, since viewMode != 'project', but I don't know that it _should_ work. :)  It seems more lucky than reasonable/correct that the label view html happens to have some element with id 'agenda_view', hence viewMode != 'project'. But maybe I misunderstand what "agenda view" means in this script? Does it just mean "not project view"?

If it helps, the project view html does have some element with class containing the string "project_view" and none of the other views do. So that could be used to accurately determine whether or not we're in project view mode.

**Comment by mgsloan** [comment]
Thanks for reporting.  I believe the fixed worked, but since then Todoist has changed.  Will track with the other issues.

**Comment by ismig** [comment]
Thanks for the fixes! All of them work...except for filter view, which unfortunately is the one I use the most.
I've tried on both beta and stable, with both multi-query and single-query filters, and I still get that error. 🤷🏼‍♂️

**Comment by mgsloan** [comment]
Ah, good point, I think I've fixed it in version 126
