### ISSUE TITLE
Chrome Extension Conflicts with Todoist's Highlighting Function

### ISSUE THREAD

**Issue by AndyHickman** [mgsloan/todoist-shortcuts#42]
If I have the todoist-shortcuts chrome extension enabled, when I try to jump to a task's exact location, I am only brought to it's general project, not it's exact location.  [Here is a screen cast demoing the issue](https://www.dropbox.com/s/vl553z9b0m97qum/zoom_0_Trim.mp4?dl=0).

**Comment by mgsloan** [comment]
Interesting!  I didn't know about that feature.  Might need to add a keybinding for it, hah!  Can't reasonably bind all the things, though.

Thanks for the report, I've pushed a fix and released version 21

**Comment by AndyHickman** [comment]
This bug is back since version 914 was released (I am using the dark mode)

**Comment by mgsloan** [comment]
@AndyHickman That appears to be an upstream Todoist issue.  I don't get the highlighting flash with the dark mode on, even with todoist-shortcuts disabled.

The dark theme is nice, though, I like it better than the stylus dark theme!  I might have to make an extension to switch between the light and dark themes based on whether it's daytime :rofl:
