### ISSUE TITLE
Cannot open scheduler for currently unscheduled tasks

### ISSUE THREAD

**Issue by ismig** [mgsloan/todoist-shortcuts#56]
When I type **t** or **T** on a task that currently has no date assigned to it, there is no response. I see the following error in the console: "Expected to find scheduler after opening it". When I try the same thing on a task that already has an assigned date, the scheduler *does* appear and things are in order.

I didn't have this problem a week ago but it started dogging me today. I tried turning on and off Todoist Beta, but no difference. :(

**Comment by mgsloan** [comment]
@ismig I saw a problem very similar to that last night, I believe it's from changes in the most recent Todoist release.  I fixed it and upload version 36 of todoist-shortcuts - does updating the extension solve the problem/

**Comment by ismig** [comment]
No, I have version 36 and it doesn't fix it for me. I restarted my browser just in case, but no luck.

**Comment by mgsloan** [comment]
Ah, you're right, this is broken.  I thought I tested this case, but I guess not.  I've uploaded version 37 with a fix.

**Comment by ismig** [comment]
Neat, it works now. Thanks for the quick fix!
